services:
    nginx:
        image: nginx:latest
        depends_on:
            - php
        volumes:
            - ./nginx-dev.conf:/etc/nginx/nginx.conf
            - ./:/app
        ports:
            - "8080:8080"
    php:
        build:
            context: .
            dockerfile: PHP.Dockerfile
        env_file:
            - .env
        volumes:
            - ./:/app
    mysql:
        image: mariadb:latest
        volumes:
            - mysqldata:/var/lib/mysql
            # - ./sql:/docker-entrypoint-initdb.d
        env_file:
            - .env
        ports:
            - 3306:3306

    phpmyadmin:
        image: phpmyadmin:latest
        volumes:
            - ./blueberry:/var/www/html/themes/blueberry
        ports:
            - 8081:80
        environment:
            - PMA_HOST=mysql
    meilisearch:
        image: getmeili/meilisearch:v1.12.8
        volumes:
            - meilisearchdata:/meili_data
        ports:
            - 7700:7700
        environment:
            - http_proxy
            - https_proxy
            - MEILI_MASTER_KEY=YOUR_MASTER_KEY
            - MEILI_SEARCH_KEY=STATIC_SEARCH_KEY
            - MEILI_NO_ANALYTICS=true
            - MEILI_ENV=development
            - MEILI_LOG_LEVEL

volumes:
    mysqldata: {}
    meilisearchdata: {}
