services:
    nginx:
        image: nginx:latest
        depends_on:
            - php
        volumes:
            - ./nginx-dev.conf:/etc/nginx/nginx.conf
            - ./:/app
        ports:
            - "8080:8080"
    php:
        build:
            context: .
            dockerfile: PHP.Dockerfile
        env_file:
            - .env
        volumes:
            - ./:/app
    mysql:
        image: mariadb:latest
        volumes:
            - mysqldata:/var/lib/mysql
            # - ./sql:/docker-entrypoint-initdb.d
        env_file:
            - .env
        ports:
            - 3306:3306

    phpmyadmin:
        image: phpmyadmin:latest
        volumes:
            - ./blueberry:/var/www/html/themes/blueberry
        ports:
            - 8081:80
        environment:
            - PMA_HOST=mysql

volumes:
    mysqldata: {}
